// import React from "react";
// import { Authform } from "./authform";
// import { Metadata } from "next";
// import { createSupabaseServerClient } from "@/lib/supabase/server";
// import { redirect } from "next/navigation";

// export const metadata: Metadata = {
//   title: "Login",
//   description: "Generated by create next app",
// };
// const Account = async () => {
//   const supabase = await createSupabaseServerClient();
//   const { data } = await supabase.auth.getUser();
//   if (data?.user) {
//     redirect("/application");
//   }
//   return (
//     <div className="flex justify-center items-center h-screen w-full bg-gray-900">
//       {/* <Authform /> */}
//     </div>
//   );
// };

// export default Account;
